import GALLERY_MANIFEST from './gallery-manifest.json';

/**
 * Gallery page content. ALL media here is PLACEHOLDER until the client's
 * real assets arrive:
 *  - Images live in public/gallery/images/ (generated by
 *    scripts/generate-gallery-images.mjs). Replace the files (same names)
 *    and update the alt/caption texts below — no other code changes needed.
 *  - Videos: drop MP4 files into public/gallery/videos/ and switch an
 *    entry to { type: 'mp4', src: '/gallery/videos/your-file.mp4' }, or set
 *    a real YouTube ID. The placeholder entries currently point at
 *    YouTube's public demo video so the lightbox is fully functional.
 */

export type GalleryImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  caption: string;
};

export type GalleryVideo = {
  id: string;
  title: string;
  desc: string;
  thumb: string;
} & ({ type: 'youtube'; youtubeId: string } | { type: 'mp4'; src: string });

/** Alt/caption text per image slot (index-aligned with the generated files). */
const IMAGE_TEXT_EN: { alt: string; caption: string }[] = [
  { alt: 'High-bay warehouse aisle with racked plastic pallets', caption: 'High-Density Warehouse — Nasr City' },
  { alt: 'Injection molding machine forming an industrial pallet', caption: 'Injection Molding Line' },
  { alt: 'Stacked export crates in the dispatch yard', caption: 'Export Dispatch Yard' },
  { alt: 'Automated conveyor moving storage bins', caption: 'Automated Handling System' },
  { alt: 'Production floor overview with molding stations', caption: 'Production Floor Overview' },
  { alt: 'Quality control inspection of finished pallets', caption: 'Quality Control Station' },
  { alt: 'Cold-chain storage room with hygienic pallets', caption: 'Cold Chain Facility' },
  { alt: 'Robotic arm handling molded components', caption: 'Robotics & Automation' },
  { alt: 'Bulk material silos feeding the production line', caption: 'Raw Material Handling' },
  { alt: 'Finished goods staged for container loading', caption: 'Container Loading Bay' },
  { alt: 'Technician calibrating molding equipment', caption: 'Precision Calibration' },
  { alt: 'Panoramic view of the manufacturing facility', caption: 'Facility Panorama' },
  { alt: 'Stacked nestable containers in storage', caption: 'Nestable Container Stock' },
  { alt: 'Pallet load stress-testing rig in action', caption: 'Load Testing Lab' },
  { alt: 'Warehouse team reviewing logistics dashboards', caption: 'Logistics Control Room' },
  { alt: 'Completed racking project for a client site', caption: 'Client Project — Racking Install' },
];


/** Arabic alt/caption text (index-aligned with the generated files). */
const IMAGE_TEXT_AR: { alt: string; caption: string }[] = [
  { alt: 'ممر مخزن عالي الارتفاع بمنصات بلاستيكية مرففة', caption: 'مخزن عالي الكثافة — مدينة نصر' },
  { alt: 'ماكينة قولبة بالحقن تُشكّل منصة صناعية', caption: 'خط القولبة بالحقن' },
  { alt: 'صناديق تصدير مكدسة في ساحة الشحن', caption: 'ساحة شحن الصادرات' },
  { alt: 'ناقل مؤتمت ينقل صناديق التخزين', caption: 'نظام مناولة مؤتمت' },
  { alt: 'نظرة عامة على أرضية الإنتاج ومحطات القولبة', caption: 'نظرة عامة على أرضية الإنتاج' },
  { alt: 'فحص ضبط جودة للمنصات الجاهزة', caption: 'محطة ضبط الجودة' },
  { alt: 'غرفة تخزين مبرد بمنصات صحية', caption: 'منشأة سلسلة التبريد' },
  { alt: 'ذراع روبوتية تناول مكونات مقولبة', caption: 'الروبوتات والأتمتة' },
  { alt: 'صوامع خامات تغذي خط الإنتاج', caption: 'مناولة المواد الخام' },
  { alt: 'بضائع جاهزة معدة لتحميل الحاويات', caption: 'رصيف تحميل الحاويات' },
  { alt: 'فني يعاير معدات القولبة', caption: 'معايرة دقيقة' },
  { alt: 'مشهد بانورامي لمنشأة التصنيع', caption: 'بانوراما المنشأة' },
  { alt: 'حاويات متداخلة مكدسة في المخزن', caption: 'مخزون الحاويات المتداخلة' },
  { alt: 'منصة اختبار إجهاد أحمال المنصات أثناء العمل', caption: 'معمل اختبارات التحميل' },
  { alt: 'فريق المخزن يراجع لوحات بيانات اللوجستيات', caption: 'غرفة تحكم اللوجستيات' },
  { alt: 'مشروع ترفيف منفذ لموقع أحد العملاء', caption: 'مشروع عميل — تركيب أرفف' },
];

/** Gallery images with text in the requested locale. */
export function galleryImages(locale: string): GalleryImage[] {
  const text = locale === 'ar' ? IMAGE_TEXT_AR : IMAGE_TEXT_EN;
  const fallback =
    locale === 'ar'
      ? { alt: 'منشأة جاينت ستوريدج', caption: 'جاينت ستوريدج' }
      : { alt: 'Giant Storage facility', caption: 'Giant Storage' };
  return (
    GALLERY_MANIFEST as { file: string; width: number; height: number }[]
  ).map((m, i) => ({
    src: m.file,
    width: m.width,
    height: m.height,
    alt: text[i]?.alt ?? fallback.alt,
    caption: text[i]?.caption ?? fallback.caption,
  }));
}

const VIDEO_TEXT_AR: Record<string, { title: string; desc: string }> = {
  'facility-tour': { title: 'داخل مصنعنا', desc: 'جولة كاملة في منشأة مدينة نصر وخطوط إنتاجها.' },
  'load-test': { title: 'اختبار تحميل المنصات شديدة التحمل', desc: 'منصات تتحمل أحمال 3 أطنان في اختبارات إجهاد مُحكمة.' },
  'export-logistics': { title: 'لوجستيات التصدير — من القاهرة إلى أوروبا', desc: 'شحن مضبوط الجودة إلى أكثر من 22 سوقًا عالميًا.' },
};

/** Gallery videos with text in the requested locale. */
export function galleryVideos(locale: string): GalleryVideo[] {
  if (locale !== 'ar') return GALLERY_VIDEOS;
  return GALLERY_VIDEOS.map((v) => ({ ...v, ...VIDEO_TEXT_AR[v.id] }));
}

/** TODO: replace the placeholder youtubeId values with the client's real videos. */
export const GALLERY_VIDEOS: GalleryVideo[] = [
  {
    id: 'facility-tour',
    title: 'Inside Our Manufacturing Plant',
    desc: 'A full tour of the Nasr City facility and its production lines.',
    thumb: '/gallery/images/img-04.jpg',
    type: 'youtube',
    youtubeId: 'M7lc1UVf-VE',
  },
  {
    id: 'load-test',
    title: 'Heavy-Duty Pallet Load Test',
    desc: 'Pallets withstanding 3-ton loads in controlled stress testing.',
    thumb: '/gallery/images/img-08.jpg',
    type: 'youtube',
    youtubeId: 'M7lc1UVf-VE',
  },
  {
    id: 'export-logistics',
    title: 'Export Logistics — Cairo to Europe',
    desc: 'Quality-controlled shipping to 22+ global markets.',
    thumb: '/gallery/images/img-12.jpg',
    type: 'youtube',
    youtubeId: 'M7lc1UVf-VE',
  },
];
