import PRODUCT_IMAGE_MANIFEST from "./product-images.json";
import { AR_COLOR_LABELS } from "./products-ar";

/**
 * Pure types + helpers only — importable from client components
 * (ProductModal.tsx). The Supabase-backed fetch functions live in
 * lib/products-data.ts (server-only).
 */

export type ProductCategory = "pallets" | "crates" | "bins" | "containers";

export type Product = {
  id: number;
  name: string;
  category: string;
  cat: ProductCategory;
  badge: string;
  status: string;
  statusClass: "status-badge-green" | "status-badge-blue" | "status-badge-amber";
  shortDesc: string;
  image: string;
  coverImage?: string;
  images?: string[];
  description: string;
  material: string;
  dimensions: string;
  loadCapacity: string;
  colors: string[];
  applications: string[];
  features: string[];
  availability: string;
};

/** Swatch hex -> human-readable name (from the legacy modal renderer). Not
 *  CMS-editable (no admin form exposes color-label translation), so this
 *  stays a static dictionary — see lib/products-ar.ts for the AR map. */
export const COLOR_LABELS: Record<string, string> = {
  "#2d6a4f": "Forest Green", "#6b7280": "Industrial Grey", "#1e40af": "Cobalt Blue", "#92400e": "Amber Brown",
  "#1f2937": "Carbon Black", "#dc2626": "Safety Red", "#16a34a": "Signal Green", "#f59e0b": "Caution Yellow",
  "#fbbf24": "Bright Yellow", "#f8fafc": "Arctic White", "#dcfce7": "Mint", "#dbeafe": "Sky Blue",
  "#fef3c7": "Cream", "#fef9c3": "Pale Yellow", "#b45309": "Terracotta", "#71717a": "Steel", "#3f3f46": "Graphite",
  "#1e3a5f": "Navy",
};

/**
 * IMAGE SETS — generated by scripts/generate-product-images.mjs into
 * public/products/product-{id}/ (cover.jpg + front/back/side/top/detail).
 * Per-product `coverImage` / `images` fields override the manifest when set.
 */
type ImageManifest = Record<string, { cover?: string; images: string[] }>;
const IMAGE_SETS = PRODUCT_IMAGE_MANIFEST as ImageManifest;

/** Featured image for the collapsed product card. */
export function productCover(product: Product): string {
  return product.coverImage ?? IMAGE_SETS[product.id]?.cover ?? product.image;
}

/** Gallery for the expanded card: explicit `images`, else the generated set, else the single catalog photo. */
export function productGallery(product: Product): string[] {
  if (product.images && product.images.length > 0) return product.images;
  const generated = IMAGE_SETS[product.id]?.images;
  if (generated && generated.length > 0) return generated;
  return [product.image];
}

/** Color swatch label in the active locale. */
export function colorLabel(hex: string, locale: string): string {
  const map = locale === "ar" ? AR_COLOR_LABELS : COLOR_LABELS;
  return map[hex] ?? hex;
}
